version: '3.8'

services:
  # Nacos
  nacos:
    image: nacos/nacos-server:v2.3.0
    container_name: nacos-server
    environment:
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_DB_NAME=nacos_devtest
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=nacos
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      - mysql
    restart: always
    networks:
      - data-platform

  # MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql-server
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=nacos_devtest
      - MYSQL_USER=nacos
      - MYSQL_PASSWORD=nacos
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - data-platform

  # Redis
  redis:
    image: redis:7-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - data-platform

  # RocketMQ NameServer
  rocketmq-nameserver:
    image: apache/rocketmq:5.1.4
    container_name: rocketmq-nameserver
    ports:
      - "9876:9876"
    environment:
      - JAVA_OPT_EXT=-server -Xms512m -Xmx512m
    command: ["sh", "mqnamesrv"]
    restart: always
    networks:
      - data-platform

  # RocketMQ Broker
  rocketmq-broker:
    image: apache/rocketmq:5.1.4
    container_name: rocketmq-broker
    ports:
      - "10909:10909"
      - "10911:10911"
    environment:
      - NAMESRV_ADDR=rocketmq-nameserver:9876
      - JAVA_OPT_EXT=-server -Xms512m -Xmx512m
    command: ["sh", "mqbroker", "-c", "/opt/rocketmq-5.1.4/conf/broker.conf"]
    depends_on:
      - rocketmq-nameserver
    restart: always
    networks:
      - data-platform

  # Elasticsearch
  elasticsearch:
    image: elasticsearch:8.9.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: always
    networks:
      - data-platform

  # MinIO
  minio:
    image: minio/minio:latest
    container_name: minio-server
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: always
    networks:
      - data-platform

  # ClickHouse
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_DB=dataplatform
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin123
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    restart: always
    networks:
      - data-platform

volumes:
  mysql_data:
  redis_data:
  es_data:
  minio_data:
  clickhouse_data:

networks:
  data-platform:
    driver: bridge